// Define an array of objects that describes our privacy policy
export const privacy = [
  {
    title: "Information we collect",
    content:
      "Personal information such as your name and email address when you subscribe to our newsletter or contact us through our contact form. Information about your device such as your IP address, browser type, and operating system. Usage data such as the pages you visit on our website and the time and date of your visit. We collect this information using cookies, which are small text files that are placed on your device when you visit our website.",
  },
  {
    title: "How we use your information",
    content:
      "Provide and improve our website and services. Respond to your inquiries and requests. Send you newsletters and other communications related to our website and services. Analyze usage of our website and services to improve our website and services. We may also use your information to comply with legal obligations or enforce our website policies.",
  },
  {
    title: "How we share your information",
    content:
      "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent. However, we may share your information with third-party service providers who help us operate our website and provide our services. We may also share your information if required by law or to protect our website, our users, or others.",
  },
  {
    title: "Links to other websites",
    content:
      "Our website may contain links to third-party websites that are not operated by us. We are not responsible for the privacy practices or content of these third-party websites.",
  },
  {
    title: "Data retention",
    content:
      "We retain your personal information for as long as necessary to provide our services and fulfill the purposes described in this privacy policy, unless a longer retention period is required or permitted by law.",
  },
  {
    title: "Your rights",
    content:
      "You have the right to access, correct, update, and delete your personal information. You may also object to or restrict the processing of your personal information. To exercise these rights, please contact us using the contact information provided below.",
  },
  {
    title: "Changes to this Privacy Policy",
    content:
      "We may update this privacy policy from time to time. We will notify you of any changes by posting the updated privacy policy on our website. The updated privacy policy will be effective as of the date of posting.",
  },
  {
    title: "Contact us",
    content:
      "If you have any questions or concerns about this privacy policy, please contact us at antirmenel@gmail.com.",
  },
];
// Define an array of objects that describes our website's features
export const about = [
  {
    title: "Wide range of recipes",
    description:
      "Our website offers a diverse selection of recipes to suit every taste and dietary requirement. From classic comfort foods to international cuisines, our collection of recipes includes something for everyone.Whether you're a seasoned cook or a beginner, our website has something to offer, and we're confident that you'll find inspiration for your next culinary adventure. ",
  },
  {
    title: "User-friendly interface",
    description:
      "Our website is optimized for mobile devices, ensuring that you can access our recipes and cooking resources from anywhere, at any time. With our user-friendly design, you can quickly and easily find the perfect recipe to satisfy your cravings and impress your family and friends.",
  },
  {
    title: "Nutritional information",
    description:
      " From calorie counts and macronutrient breakdowns to ingredient lists and allergen information, we aim to provide our users with all the information they need to make informed decisions about their meals. Our recipes are designed to cater to a range of dietary needs and preferences, including vegetarian, vegan, and gluten-free options. ",
  },
  {
    title: "Personalized experience",
    description:
      "Our advanced search and filtering options allow users to easily find recipes that fit their specific requirements. We also provide recommendations based on a user's search history and past recipe interactions, making the recipe selection process even more personalized. ",
  },
];

export const allRecipes = [
  {
    id: 1,
    name: "Avocado and Tomato Salad",
    description:
      "This delicious and refreshing salad is packed with healthy fats and nutrients from avocado and tomatoes.",
    ingredients: [
      "2 ripe avocados",
      "2 cups cherry tomatoes, halved",
      "1/2 small red onion, sliced",
      "2 tablespoons chopped fresh cilantro",
      "1 tablespoon olive oil",
      "1 tablespoon lime juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine avocado, cherry tomatoes, red onion, and cilantro.",
      "Drizzle with olive oil and lime juice.",
      "Season with salt and pepper to taste.",
      "Toss gently to combine.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/3c845780-9a56-49a3-868e-41afef0cabcb/Leonardo_Creative_Generate_a_highquality_realistic_photo_of_an_4.jpg",
    prep_time: "10 minutes",
    cook_time: "0 minutes",
    total_time: "10 minutes",
    y_ield: "4 servings",
    calories: "230 per serving",
    dietary_restrictions: ["vegetarian", "gluten-free", "dairy-free"],
    type: "healthy",
  },
  {
    id: 2,
    name: "Grilled Chicken with Mixed Vegetables",
    description:
      "This flavorful and protein-packed dish is perfect for a healthy and satisfying meal.",
    ingredients: [
      "4 boneless, skinless chicken breasts",
      "2 zucchinis, sliced",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1/4 cup olive oil",
      "2 tablespoons balsamic vinegar",
      "2 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "In a small bowl, whisk together olive oil, balsamic vinegar, garlic, oregano, salt, and pepper.",
      "In a large bowl, toss together chicken, zucchinis, red bell pepper, yellow bell pepper, and the olive oil mixture.",
      "Grill the chicken and vegetables for 5-7 minutes per side, or until the chicken is cooked through and the vegetables are tender.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/ff527280-65c8-40bb-b0af-cce5455af23d/Leonardo_Creative_highquality_realistic_photo_of_Grilled_Chick_4.jpg",
    prep_time: "15 minutes",
    cook_time: "15 minutes",
    total_time: "30 minutes",
    y_ield: "4 servings",
    calories: "300 per serving",
    dietary_restrictions: ["gluten-free", "dairy-free"],
    type: "healthy",
  },
  {
    id: 3,
    name: "Roasted Salmon with Asparagus and Potatoes",
    description:
      "This healthy and easy-to-make dish is packed with protein, fiber, and healthy fats. Perfect for a quick weeknight dinner!",
    ingredients: [
      "4 salmon fillets",
      "1 pound asparagus, trimmed",
      "1 pound baby potatoes, halved",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "1 tablespoon fresh rosemary, chopped",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "In a large bowl, toss together asparagus, potatoes, olive oil, garlic, rosemary, salt, and pepper.",
      "Spread the vegetables in a single layer on a large baking sheet.",
      "Place the salmon fillets on top of the vegetables.",
      "Bake for 15-20 minutes, or until the salmon is cooked through and the vegetables are tender.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/f49d7714-f186-446e-b768-b595b6f1633e/Leonardo_Creative_highquality_realistic_photo_of_Roasted_Salmo_3.jpg",
    prep_time: "10 minutes",
    cook_time: "20 minutes",
    total_time: "30 minutes",
    y_ield: "4 servings",
    calories: "350 per serving",
    dietary_restrictions: ["gluten-free", "dairy-free"],
    type: "healthy",
  },
  {
    id: 4,
    name: "Quinoa Salad with Chickpeas and Roasted Vegetables",
    description:
      "This colorful and flavorful salad is packed with plant-based protein and fiber. Perfect for a healthy and satisfying lunch!",
    ingredients: [
      "1 cup quinoa",
      "2 cups water",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 small red onion, sliced",
      "1 can chickpeas, drained and rinsed",
      "2 tablespoons olive oil",
      "2 tablespoons balsamic vinegar",
      "1 tablespoon honey",
      "1 tablespoon Dijon mustard",
      "1/4 cup fresh parsley, chopped",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "In a medium saucepan, combine quinoa and water. Bring to a boil, then reduce heat and simmer for 15-20 minutes, or until quinoa is cooked and water is absorbed.",
      "In a large bowl, toss together bell peppers, onion, chickpeas, olive oil, salt, and pepper.",
      "Spread the vegetables in a single layer on a large baking sheet.",
      "Roast the vegetables for 15-20 minutes, or until tender and lightly charred.",
      "In a small bowl, whisk together balsamic vinegar, honey, Dijon mustard, salt, and pepper.",
      "In a large bowl, combine cooked quinoa, roasted vegetables, and dressing.",
      "Toss gently to combine.",
      "Sprinkle with chopped parsley.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/41d8f8b7-47fe-4f26-b89a-9d94be814e66/Leonardo_Creative_highquality_realistic_photo_of_Quinoa_Salad_0.jpg",
    prep_time: "10 minutes",
    cook_time: "20 minutes",
    total_time: "30 minutes",
    y_ield: "4 servings",
    calories: "300 per serving",
    type: "healthy",
  },
  {
    id: 5,
    name: "Quinoa and Black Bean Salad",
    description:
      "This hearty and flavorful salad is packed with plant-based protein and fiber from quinoa and black beans.",
    ingredients: [
      "1 cup quinoa, rinsed and drained",
      "1 can black beans, rinsed and drained",
      "1 red bell pepper, diced",
      "1/2 red onion, diced",
      "1/4 cup chopped fresh cilantro",
      "2 tablespoons olive oil",
      "2 tablespoons lime juice",
      "1 teaspoon ground cumin",
      "1/2 teaspoon chili powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a medium saucepan, bring 2 cups of water to a boil.",
      "Add quinoa and reduce heat to low.",
      "Cover and simmer for 15-20 minutes, or until the quinoa is tender and the water is absorbed.",
      "In a large bowl, combine quinoa, black beans, red bell pepper, red onion, and cilantro.",
      "In a small bowl, whisk together olive oil, lime juice, cumin, chili powder, salt, and pepper.",
      "Drizzle the dressing over the salad and toss to combine.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/382d54ce-7e21-4c9f-97d6-ba34be733c6e/Leonardo_Creative_highquality_realistic_photo_of_Quinoa_and_Bl_0.jpg",
    prep_time: "10 minutes",
    cook_time: "20 minutes",
    total_time: "30 minutes",
    y_ield: "4 servings",
    calories: "320 per serving",
    dietary_restrictions: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    type: "healthy",
  },
  {
    id: 6,
    name: "Baked Salmon with Roasted Vegetables",
    description:
      "This delicious and nutritious dish features heart-healthy salmon and a variety of colorful roasted vegetables.",
    ingredients: [
      "4 salmon fillets",
      "1 small head of broccoli, chopped",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 small zucchini, sliced",
      "2 tablespoons olive oil",
      "1 tablespoon honey",
      "1 tablespoon Dijon mustard",
      "1 tablespoon chopped fresh thyme",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "In a large bowl, whisk together olive oil, honey, Dijon mustard, thyme, salt, and pepper.",
      "Add salmon fillets and vegetables to the bowl and toss to coat with the marinade.",
      "Arrange salmon and vegetables in a single layer on a large baking sheet.",
      "Bake for 15-20 minutes, or until the salmon is cooked through and the vegetables are tender.",
      "Serve and enjoy!",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/f822bb8e-52b7-4487-893b-823b65572dec/Leonardo_Creative_highquality_realistic_photo_of_Baked_Salmon_5.jpg",
    prep_time: "15 minutes",
    cook_time: "20 minutes",
    total_time: "35 minutes",
    y_ield: "4 servings",
    calories: "350 per serving",
    dietary_restrictions: ["gluten-free", "dairy-free"],
    type: "healthy",
  },
  {
    id: 7,
    name: "Bacon-Wrapped Jalapeno Poppers",
    description:
      "These spicy and cheesy appetizers are wrapped in crispy bacon for the ultimate indulgence.",
    ingredients: [
      "12 jalapeno peppers",
      "4 ounces cream cheese, softened",
      "1/2 cup shredded cheddar cheese",
      "12 slices bacon",
      "Toothpicks",
    ],
    instructions: [
      "Preheat the oven to 375°F. Line a baking sheet with parchment paper.",
      "Slice each jalapeno pepper in half lengthwise and remove the seeds and membranes with a spoon.",
      "In a mixing bowl, combine the cream cheese and shredded cheddar cheese.",
      "Stuff each jalapeno half with the cheese mixture and wrap with a slice of bacon. Secure with a toothpick.",
      "Place the jalapeno poppers on the prepared baking sheet and bake for 20-25 minutes or until the bacon is crispy and the cheese is melted.",
      "Remove from the oven and let cool for a few minutes before serving.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/b142a5d8-68ce-499d-b5ad-34acc6f514ba/Leonardo_Creative_highquality_realistic_photo_of_BaconWrapped_1.jpg",
    prep_time: "15 minutes",
    cook_time: "20-25 minutes",
    total_time: "35-40 minutes",
    y_ield: "24 poppers",
    calories: "120 per serving",
    dietary_restrictions: [],
    type: "trendy",
  },
  {
    id: 8,
    name: "Crispy Fried Chicken Sandwich",
    description:
      "This indulgent sandwich features juicy fried chicken, tangy pickles, and spicy mayo, all served on a fluffy brioche bun.",
    ingredients: [
      "4 boneless, skinless chicken breasts",
      "1 cup all-purpose flour",
      "1 tablespoon garlic powder",
      "1 tablespoon paprika",
      "1 teaspoon cayenne pepper",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "1 cup buttermilk",
      "1 large egg",
      "1 tablespoon hot sauce",
      "1 cup panko bread crumbs",
      "1/2 cup mayonnaise",
      "2 tablespoons hot sauce",
      "1 tablespoon honey",
      "4 brioche buns",
      "8-12 slices dill pickles",
      "4 lettuce leaves",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "Pound chicken breasts to an even thickness.",
      "In a shallow dish, whisk together flour, garlic powder, paprika, cayenne, salt, and black pepper.",
      "In another shallow dish, whisk together buttermilk, egg, and hot sauce.",
      "In a third shallow dish, place panko bread crumbs.",
      "Dredge chicken in flour mixture, then dip in buttermilk mixture, and coat in panko breadcrumbs.",
      "Heat 1/2 inch oil in a large skillet over medium-high heat. Fry chicken until golden brown and cooked through, about 4-5 minutes per side. Drain on paper towels.",
      "In a small bowl, whisk together mayonnaise, hot sauce, and honey.",
      "Toast brioche buns until lightly browned.",
      "To assemble sandwiches, spread spicy mayo on bottom bun, top with lettuce, fried chicken, pickles, and top bun. Serve immediately.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/9a9d6579-f3a9-4e63-a32a-1722e10ad983/Leonardo_Creative_highquality_realistic_photo_of_Crispy_Fried_2.jpg",
    prep_time: "20 minutes",
    cook_time: "20 minutes",
    total_time: "40 minutes",
    y_ield: "4 sandwiches",
    calories: "600 per serving",
    dietary_restrictions: [],
    type: "trendy",
  },
  {
    id: 9,
    name: "Buffalo Chicken Dip",
    description:
      "This crowd-pleasing dip is a spicy and creamy combination of shredded chicken, cream cheese, hot sauce, and blue cheese dressing.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "8 oz cream cheese, softened",
      "1/2 cup hot sauce",
      "1/2 cup blue cheese dressing",
      "1/2 cup shredded cheddar cheese",
      "1/4 cup sliced green onions",
      "Tortilla chips or celery sticks, for serving",
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "In a large bowl, combine shredded chicken, cream cheese, hot sauce, blue cheese dressing, cheddar cheese, and green onions.",
      "Spread the mixture into an oven-safe dish.",
      "Bake for 20-25 minutes or until the dip is hot and bubbly.",
      "Serve with tortilla chips or celery sticks.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/f4891717-24c9-4d96-a8dd-6faa3fc48fb9/Leonardo_Creative_highquality_realistic_photo_of_Buffalo_Chick_0.jpg",
    prep_time: "10 minutes",
    cook_time: "20 minutes",
    total_time: "30 minutes",
    y_ield: "8 servings",
    calories: "310 per serving",
    dietary_restrictions: [],
    type: "trendy",
  },
  {
    id: 10,
    name: "Deep Fried Chicken Wings",
    description:
      "These crispy and flavorful chicken wings are a crowd-pleaser and perfect for game day or parties.",
    ingredients: [
      "2 pounds chicken wings",
      "1 cup all-purpose flour",
      "1 teaspoon garlic powder",
      "1 teaspoon paprika",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "1/2 cup hot sauce",
      "1/4 cup butter, melted",
      "Oil for frying",
    ],
    instructions: [
      "In a large bowl, combine flour, garlic powder, paprika, salt, and black pepper.",
      "Add chicken wings and toss to coat.",
      "In a deep skillet or Dutch oven, heat oil over medium-high heat to 375°F.",
      "Add chicken wings to the hot oil and fry until golden brown and crispy, about 8-10 minutes.",
      "In a separate bowl, whisk together hot sauce and melted butter.",
      "Toss fried chicken wings in the hot sauce mixture and serve immediately.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/7bda429c-c863-40e1-a208-b44f8b571abc/Leonardo_Creative_highquality_realistic_photo_of_Deep_Fried_Ch_5.jpg",
    prep_time: "15 minutes",
    cook_time: "10 minutes",
    total_time: "25 minutes",
    y_ield: "4-6 servings",
    calories: "300 per serving",
    dietary_restrictions: [],
    type: "trendy",
  },
  {
    id: 11,
    name: "Roast Beef with Garlic and Rosemary",
    description:
      "This tender and flavorful roast beef is perfect for a special occasion dinner.",
    ingredients: [
      "1 (3-pound) boneless beef rib roast",
      "4 cloves garlic, minced",
      "2 tablespoons chopped fresh rosemary",
      "1 tablespoon olive oil",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
    ],
    instructions: [
      "Preheat oven to 450°F.",
      "In a small bowl, combine garlic, rosemary, olive oil, salt, and black pepper.",
      "Rub the mixture all over the roast.",
      "Place the roast on a rack in a roasting pan and roast for 15 minutes.",
      "Reduce oven temperature to 350°F and continue roasting for 1 1/2 to 2 hours, or until a meat thermometer inserted into the center of the roast registers 135°F for medium-rare.",
      "Remove roast from oven and let it rest for 10 minutes before carving.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/d663779a-0de3-453b-88af-ca10b3fe2275/Leonardo_Creative_highquality_realistic_photo_of_Roast_Beef_wi_4.jpg",
    prep_time: "15 minutes",
    cook_time: "2 hours",
    total_time: "2 hours 15 minutes",
    yield: "6-8 servings",
    calories: "350 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 12,
    name: "Holiday Sugar Cookies",
    description:
      "These classic sugar cookies are perfect for the holidays, and can be decorated with your favorite icing and sprinkles.",
    ingredients: [
      "2 1/2 cups all-purpose flour",
      "1 teaspoon baking powder",
      "1/2 teaspoon salt",
      "1 cup unsalted butter, at room temperature",
      "1 cup granulated sugar",
      "1 large egg",
      "1 teaspoon vanilla extract",
    ],
    instructions: [
      "In a medium bowl, whisk together flour, baking powder, and salt.",
      "In a large bowl, beat butter and sugar together until light and fluffy, about 3-4 minutes.",
      "Add egg and vanilla extract, and beat until well combined.",
      "Add flour mixture to the butter mixture in three parts, mixing until just combined after each addition.",
      "Divide dough in half and wrap each half in plastic wrap. Chill for at least 1 hour.",
      "Preheat oven to 350°F. Line baking sheets with parchment paper.",
      "Roll out dough on a floured surface to 1/4-inch thickness. Cut out cookies with cookie cutters and transfer to prepared baking sheets.",
      "Bake cookies for 8-10 minutes, or until edges are lightly golden brown. Let cool on baking sheets for 5 minutes, then transfer to wire racks to cool completely.",
      "Decorate cookies with your favorite icing and sprinkles.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/1ce40bdc-776b-463c-a5dd-d27ddb2e4678/Leonardo_Creative_highquality_realistic_photo_of_Holiday_Sugar_7.jpg",
    prep_time: "1 hour 30 minutes",
    cook_time: "10 minutes",
    total_time: "1 hour 40 minutes",
    y_ield: "24-30 cookies",
    calories: "150 per cookie",
    dietary_restrictions: ["vegetarian"],
    type: "special occasion",
  },
  {
    id: 13,
    name: "Lobster Bisque",
    description:
      "This creamy and luxurious soup is a classic French dish that's perfect for special occasions.",
    ingredients: [
      "2 live lobsters",
      "4 tablespoons unsalted butter",
      "1 onion, chopped",
      "2 carrots, chopped",
      "2 celery stalks, chopped",
      "4 garlic cloves, chopped",
      "1/4 cup all-purpose flour",
      "1/2 cup brandy",
      "4 cups seafood stock",
      "1 cup heavy cream",
      "1 tablespoon tomato paste",
      "1 teaspoon paprika",
      "1 bay leaf",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Bring a large pot of salted water to a boil. Add the lobsters and cook for 8 minutes. Remove the lobsters and let cool. Reserve the cooking liquid.",
      "Remove the meat from the lobster tails, claws, and knuckles. Cut the meat into small pieces and set aside. Reserve the shells.",
      "In a large pot or Dutch oven, melt the butter over medium heat. Add the onion, carrots, celery, and garlic. Cook for 10-12 minutes, until softened.",
      "Add the flour and stir to coat the vegetables. Cook for 2-3 minutes, stirring constantly.",
      "Add the brandy and cook for 2-3 minutes, until the alcohol has evaporated.",
      "Add the seafood stock, reserved lobster cooking liquid, heavy cream, tomato paste, paprika, bay leaf, and lobster shells. Bring to a boil, then reduce the heat and simmer for 30-40 minutes, until the soup has thickened and the flavors have developed.",
      "Remove the lobster shells and bay leaf. Puree the soup with an immersion blender or in batches in a blender or food processor.",
      "Return the soup to the pot and add the lobster meat. Simmer for 5-10 minutes, until the lobster is heated through. Season with salt and pepper to taste.",
      "Serve hot, garnished with chopped fresh herbs if desired.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/acd79570-2aba-45cf-b8c2-1a6823871404/Leonardo_Creative_highquality_realistic_photo_of_Lobster_Bisqu_5.jpg",
    prep_time: "30 minutes",
    cook_time: "1 hour",
    total_time: "1 hour 30 minutes",
    yield: "6 servings",
    calories: "500 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 14,
    name: "Creamy Tomato Soup",
    description:
      "This creamy tomato soup is comfort in a bowl. Made with simple ingredients, it's easy to make and perfect for a cozy night in.",
    ingredients: [
      "1 tablespoon olive oil",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "2 cans (28 ounces) whole peeled tomatoes",
      "1 cup vegetable broth",
      "1/2 cup heavy cream",
      "1 teaspoon dried basil",
      "1/2 teaspoon dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large pot, heat olive oil over medium heat. Add onion and garlic and sauté until softened, about 5 minutes.",
      "Add canned tomatoes (with juices) and vegetable broth. Bring to a simmer and let cook for 15 minutes.",
      "Using an immersion blender, blend soup until smooth. (Alternatively, transfer soup to a blender and blend until smooth, then return to pot.)",
      "Add heavy cream, dried basil, and dried oregano. Season with salt and pepper to taste.",
      "Let soup simmer for an additional 5-10 minutes to allow flavors to meld. Serve hot with your favorite bread or crackers.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/dc9dda1d-1e92-4483-9f68-9f406824f693/Leonardo_Creative_highquality_realistic_photo_of_Creamy_Tomato_5.jpg",
    prep_time: "10 minutes",
    cook_time: "30 minutes",
    total_time: "40 minutes",
    y_ield: "4-6 servings",
    calories: "250 per serving",
    dietary_restrictions: ["vegetarian"],
    type: "special occasion",
  },
  {
    id: 15,
    name: "Classic Lasagna",
    description:
      "This classic lasagna recipe is a family favorite and perfect for special occasions or a cozy weekend dinner.",
    ingredients: [
      "1 pound lean ground beef",
      "1 large onion, chopped",
      "2 cloves garlic, minced",
      "1 can (28 ounces) crushed tomatoes",
      "1 can (6 ounces) tomato paste",
      "1/4 cup water",
      "2 tablespoons sugar",
      "1 teaspoon dried basil leaves",
      "1 teaspoon fennel seeds",
      "1 teaspoon Italian seasoning",
      "1 tablespoon salt",
      "1/4 teaspoon black pepper",
      "4 cups shredded mozzarella cheese",
      "1 1/2 cups ricotta cheese",
      "1/2 cup grated Parmesan cheese",
      "12 lasagna noodles",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "In a large skillet, cook ground beef, onion, and garlic over medium heat until meat is browned; drain.",
      "Stir in crushed tomatoes, tomato paste, water, sugar, basil, fennel seeds, Italian seasoning, salt, and pepper.",
      "Bring to a boil; reduce heat and simmer uncovered for 30 minutes.",
      "Meanwhile, cook lasagna noodles according to package directions; drain.",
      "In a medium bowl, combine mozzarella, ricotta, and Parmesan cheeses.",
      "Spread 1 cup of the meat sauce in the bottom of a 9x13 inch baking dish.",
      "Layer with 3 lasagna noodles, 1/3 of the cheese mixture, and 1 cup of meat sauce.",
      "Repeat layers twice.",
      "Cover with foil and bake for 25 minutes.",
      "Remove foil and bake for an additional 25 minutes or until cheese is melted and bubbly.",
      "Let stand for 10 minutes before serving.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/d7d99475-805f-4d9f-9c4a-08a45ef6c9c0/Leonardo_Creative_highquality_realistic_photo_of_Classic_Lasag_3.jpg",
    prep_time: "30 minutes",
    cook_time: "1 hour",
    total_time: "1 hour 30 minutes",
    y_ield: "8 servings",
    calories: "540 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 16,
    name: "Beef Stroganoff",
    description:
      "A classic Russian dish made with tender strips of beef, mushrooms, and sour cream. Perfect for a cozy night in!",
    ingredients: [
      "1 pound beef sirloin, thinly sliced",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "8 ounces mushrooms, sliced",
      "1 tablespoon olive oil",
      "2 tablespoons butter",
      "2 tablespoons all-purpose flour",
      "1 cup beef broth",
      "1/2 cup sour cream",
      "1 tablespoon Dijon mustard",
      "Salt and black pepper to taste",
      "8 ounces egg noodles, cooked according to package instructions",
      "2 tablespoons chopped fresh parsley",
    ],
    instructions: [
      "In a large skillet, heat the olive oil over medium-high heat. Add the beef and cook until browned on all sides, about 5 minutes. Remove the beef from the skillet and set aside.",
      "In the same skillet, add the onion and garlic and sauté until soft, about 3-4 minutes. Add the mushrooms and cook until they release their liquid, about 5 minutes.",
      "Remove the mushroom mixture from the skillet and set aside.",
      "In the same skillet, melt the butter over medium heat. Add the flour and whisk to combine. Cook for 2-3 minutes, whisking constantly.",
      "Slowly whisk in the beef broth and bring to a simmer. Cook until the sauce thickens, about 5 minutes.",
      "Add the sour cream and Dijon mustard to the sauce and whisk to combine. Cook for 2-3 minutes, stirring constantly.",
      "Add the beef and mushroom mixture to the sauce and stir to combine. Cook until the beef is heated through, about 5 minutes.",
      "Season with salt and black pepper to taste.",
      "Serve the beef stroganoff over the cooked egg noodles, garnished with chopped fresh parsley.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/9c887d06-511e-4c20-b84f-0fc841044532/Leonardo_Creative_highquality_realistic_photo_of_Beef_Strogano_3.jpg",
    prep_time: "15 minutes",
    cook_time: "30 minutes",
    total_time: "45 minutes",
    yield: "4-6 servings",
    calories: "400 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 17,
    name: "Beef Wellington",
    description:
      "A classic and elegant dish that's perfect for special occasions. Tender beef filet coated in a savory mushroom mixture, wrapped in puff pastry and baked to golden perfection.",
    ingredients: [
      "1 (2-pound) beef tenderloin, trimmed",
      "1 tablespoon vegetable oil",
      "1/2 cup minced shallots",
      "8 ounces mushrooms, finely chopped",
      "1/4 cup dry white wine",
      "2 tablespoons Dijon mustard",
      "1 teaspoon chopped fresh thyme",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 cup chopped fresh parsley",
      "1 pound puff pastry, thawed",
      "1 egg yolk, beaten with 1 tablespoon water",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Season beef with salt and pepper. Heat oil in a large skillet over high heat. Add beef and sear on all sides until browned, about 2-3 minutes per side. Transfer beef to a plate and let cool.",
      "In the same skillet, add shallots and mushrooms and cook over medium heat until softened, about 5 minutes. Add wine and cook until evaporated. Stir in mustard, thyme, salt, pepper, and parsley. Remove from heat and let cool.",
      "Roll out puff pastry on a lightly floured surface into a rectangle large enough to wrap around the beef. Spread the mushroom mixture evenly over the pastry, leaving a border around the edges.",
      "Place beef in the center of the pastry and wrap the pastry around the beef, pressing the edges to seal. Place seam-side down on a baking sheet and brush with the egg wash.",
      "Bake for 35-40 minutes, until the pastry is golden brown and the beef is cooked to your desired level of doneness.",
      "Let rest for 10 minutes before slicing and serving.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/be160b19-5d31-42a2-9be9-ebf0716ef0ae/Leonardo_Creative_highquality_realistic_photo_of_Beef_Wellingt_4.jpg",
    prep_time: "30 minutes",
    cook_time: "45 minutes",
    total_time: "1 hour 15 minutes",
    yield: "6-8 servings",
    calories: "600 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 18,
    name: "Herb-Crusted Rack of Lamb",
    description:
      "This herb-crusted rack of lamb is an elegant and flavorful main dish for a special occasion dinner.",
    ingredients: [
      "2 racks of lamb, frenched",
      "2 tablespoons Dijon mustard",
      "2 tablespoons fresh rosemary, chopped",
      "2 tablespoons fresh thyme, chopped",
      "2 cloves garlic, minced",
      "1/2 cup panko bread crumbs",
      "Salt and black pepper to taste",
      "2 tablespoons olive oil",
    ],
    instructions: [
      "Preheat the oven to 400°F (200°C).",
      "In a small bowl, mix together the mustard, rosemary, thyme, and garlic.",
      "Season the racks of lamb with salt and black pepper, then brush with the mustard mixture.",
      "In another bowl, mix together the panko bread crumbs and olive oil.",
      "Press the bread crumb mixture onto the mustard-coated racks of lamb, covering the meat evenly.",
      "Place the racks of lamb in a baking dish and roast for 20-25 minutes for medium-rare, or until the internal temperature reaches 130°F (55°C).",
      "Remove the lamb from the oven and let it rest for 5-10 minutes before slicing and serving.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/584e4c54-9bd4-4be5-9636-9e82e99203d4/Leonardo_Creative_highquality_realistic_photo_of_HerbCrusted_R_2.jpg",
    prep_time: "15 minutes",
    cook_time: "25 minutes",
    total_time: "40 minutes",
    yield: "4 servings",
    calories: "400 per serving",
    dietary_restrictions: [],
    type: "special occasion",
  },
  {
    id: 19,
    name: "Pesto Pasta",
    description:
      "This simple and delicious pesto pasta is perfect for a quick and easy weeknight dinner.",
    ingredients: [
      "1 pound pasta",
      "1/2 cup basil pesto",
      "1/4 cup grated Parmesan cheese",
      "Salt and black pepper to taste",
    ],
    instructions: [
      "Cook the pasta according to the package instructions in a large pot of salted boiling water.",
      "Reserve 1/2 cup of the pasta cooking water, then drain the pasta.",
      "Return the pasta to the pot and add the pesto and Parmesan cheese.",
      "Toss the pasta until well coated, adding reserved pasta water as needed to thin the sauce to your desired consistency.",
      "Season with salt and black pepper to taste.",
      "Serve immediately.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/b53a6717-22e1-44ff-850b-7f362b186f5d/Leonardo_Creative_highquality_realistic_photo_of_Pesto_Pasta_w_4.jpg",
    prep_time: "5 minutes",
    cook_time: "15 minutes",
    total_time: "20 minutes",
    yield: "4-6 servings",
    calories: "350 per serving",
    dietary_restrictions: [],
    type: "quick",
  },
  {
    id: 20,
    name: "Caprese Salad",
    description:
      "This classic Italian salad is made with fresh mozzarella, juicy tomatoes, and aromatic basil. It's a simple and refreshing side dish that's perfect for a quick and easy meal.",
    ingredients: [
      "2 large ripe tomatoes",
      "8 ounces fresh mozzarella cheese",
      "1/4 cup fresh basil leaves",
      "2 tablespoons balsamic vinegar",
      "2 tablespoons olive oil",
      "Salt and black pepper to taste",
    ],
    instructions: [
      "Slice the tomatoes and mozzarella into 1/4-inch-thick slices.",
      "Arrange the tomato and mozzarella slices on a serving platter, alternating them.",
      "Scatter the fresh basil leaves over the top of the tomato and mozzarella slices.",
      "Drizzle the balsamic vinegar and olive oil over the top of the salad.",
      "Season with salt and black pepper to taste.",
      "Serve immediately.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/d8a815bb-34e7-4b60-8756-1cb9f80bbf2e/Leonardo_Creative_highquality_realistic_photo_of_Caprese_Salad_0.jpg",
    prep_time: "10 minutes",
    cook_time: "",
    total_time: "10 minutes",
    yield: "4 servings",
    calories: "250 per serving",
    dietary_restrictions: ["Vegetarian"],
    type: "quick",
  },
  {
    id: 21,
    name: "Easy Chicken Stir-Fry",
    description:
      "This quick and easy chicken stir-fry is a flavorful and healthy dinner option that's ready in no time!",
    ingredients: [
      "1 lb boneless, skinless chicken breasts, cut into bite-sized pieces",
      "2 tablespoons vegetable oil",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 small onion, sliced",
      "2 garlic cloves, minced",
      "1 tablespoon fresh ginger, minced",
      "1/4 cup soy sauce",
      "1 tablespoon honey",
      "1 tablespoon cornstarch",
      "1/4 cup chicken broth",
      "1/4 cup chopped scallions, for garnish",
    ],
    instructions: [
      "Heat 1 tablespoon of the vegetable oil in a large skillet over medium-high heat. Add the chicken and cook for 5-7 minutes, or until browned on all sides and cooked through. Remove from the skillet and set aside.",
      "Add the remaining tablespoon of vegetable oil to the skillet. Add the bell peppers and onion and sauté for 3-4 minutes, or until softened.",
      "Add the garlic and ginger and sauté for an additional 1-2 minutes.",
      "In a small bowl, whisk together the soy sauce, honey, cornstarch, and chicken broth.",
      "Add the chicken back to the skillet and pour the sauce over the top. Stir to combine and cook for an additional 2-3 minutes, or until the sauce has thickened and the chicken is heated through.",
      "Serve hot, garnished with chopped scallions.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/a3342224-ec50-4686-a445-fe6fb391e547/Leonardo_Creative_highquality_realistic_photo_of_Easy_Chicken_0.jpg",
    prep_time: "10 minutes",
    cook_time: "15 minutes",
    total_time: "25 minutes",
    yield: "4 servings",
    calories: "300 per serving",
    dietary_restrictions: ["Gluten-free"],
    type: "quick",
  },
  {
    id: 22,
    name: "Stir-Fry Vegetables with Tofu",
    description:
      "This stir-fry vegetables with tofu is a healthy and delicious vegan meal that can be made in under 30 minutes!",
    ingredients: [
      "1 package firm tofu, drained and cubed",
      "2 tablespoons vegetable oil",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 onion, sliced",
      "2 cups sliced mushrooms",
      "2 cups broccoli florets",
      "1/4 cup soy sauce",
      "1/4 cup hoisin sauce",
      "2 tablespoons cornstarch",
      "2 tablespoons water",
      "Salt and black pepper to taste",
    ],
    instructions: [
      "Heat the vegetable oil in a wok or large skillet over high heat. Add the cubed tofu and stir-fry for 5-7 minutes, or until golden brown. Remove the tofu from the pan and set aside.",
      "In the same pan, add the sliced bell peppers, onion, mushrooms, and broccoli. Stir-fry for 5-7 minutes, or until the vegetables are crisp-tender.",
      "In a small bowl, whisk together the soy sauce, hoisin sauce, cornstarch, water, salt, and black pepper.",
      "Add the cooked tofu back to the pan with the vegetables. Pour the sauce over the top and stir-fry for 1-2 minutes, or until the sauce has thickened and the vegetables and tofu are coated.",
      "Serve hot over rice or noodles.",
    ],
    image_url:
      "https://cdn.leonardo.ai/users/8a4d8e21-1e52-4a7b-8623-01f7d048dfd3/generations/d943059e-0203-46dc-9348-29b165263a50/Leonardo_Creative_highquality_realistic_photo_of_StirFry_Veget_2.jpg",
    prep_time: "15 minutes",
    cook_time: "10 minutes",
    total_time: "25 minutes",
    yield: "4 servings",
    calories: "250 per serving",
    dietary_restrictions: ["Vegan"],
    type: "quick",
  },
];
export const navLinks = [
  { href: "/", text: "HOME" },
  { href: "/recipes", text: "RECIPES" },
  { href: "/quick", text: "QUICK AND EASY" },
  { href: "/occasions", text: "OCCASIONS" },
  { href: "/trends", text: "TRENDS" },
];
export const testimonialsData = [
  {
    text: "since finding this website, I now have endless options for easy, healthy, and delicious recipes! With step-by-step instructions and photos, the recipes are simple to follow and use ingredients I already have in my kitchen. Thanks to this website, I've become more confident in my cooking abilities and love making meals for my family.",
    author: "Holden Caulfield",
  },
  {
    text: "Wow, I am so impressed with the variety of recipes available on this website! From quick and easy weeknight dinners to decadent desserts for special occasions, there's something for every taste and skill level. I have tried several recipes already and they have all turned out delicious. Thank you for helping me expand my cooking repertoire!",
    author: "John Doe",
  },
];
